### PR TITLE
Update to Volume field to be data type of long

### PR DESCRIPTION
**Pull request by longpshorn**
Updating Historical Quote Day object to use a long data type for the Volume field as there are securities with volume that exceeds the data size of an int.

I pulled a lot of data recently and found that the int data type was not sufficiently large for the data retrieved.

### CODE REVIEW

**Comment by vitali-karmanov** [comment]
Hey Patrick,

Thank you for sending the changes. I will review them and create a new NuGet Package later tonight.

**Comment by longpshorn** [comment]
Hi Vitali. Thanks for taking a look and considering them. I know that the update to fix the issue where I was seeing a bug is pretty hacky, so I am happy to get feedback on that.

Also though, I have some other changes I was holding back that provide a rough streaming implementation. I was also starting to stub out some of the Fundamentals endpoints as well. So, I wanted to let you know in case you wanted to hold off on creating the nuget package until I shared these other changes.

**Comment by vitali-karmanov** [comment]
Hey Patrick, I will love to see your implementation for streaming and for the fundamentals. However, could you create a new pull request with those changes? Like you mentioned, I like the idea of keeping new features and fixes in different pull requests.

Also, do you mind sending me an example of two HistoricalQuotes requests that you had problems with so I can test your solutions?

Thank you!

**Comment by longpshorn** [comment]
I will put together a pull request for those additional changes.

I was also considering adding a test project to the solution so that I can share both the examples that failed for me for the HistoricalQuotes, and so that you can see how my streaming implementation can be used. I am testing it with a little CLI, but that is for another application I am working on. I think it would be really beneficial to have a simple testing project associated with TradierClient project. Would you be ok with me adding a testing project?

**Comment by longpshorn** [comment]
In my latest commit, I added a test project. Right now, it just has the two tests of the GetHistoricalQuotes method in the MarketData object.

The first test is for when the request spans more than a single day. The second test is for when the request is for only a single day. This is the test case that I was having a problem with and made the suggested change. If you comment out my changes in GetHistoricalQuotes and run the test, you will see that it fails.

In order to run the test project, you will have to set up a user secrets file for the project. I included in the comments of the appsettings.json how you can go about doing this, but let me know if something doesn't work out for you.

Let me know your thoughts.

**Comment by vitali-karmanov** [comment]
Awesome, I will give it a try right now!

**Comment by longpshorn** [comment]
I had to make one more quick update because I had a mistake with one of my namespaces. Sorry.

**Review by vitali-karmanov — APPROVED** [review]
First off all, thank you so much for adding the Test Project! @htedeschi and I loved the idea and the way that you implemented it.

The project worked like a charm and we were able to successfully create the secret file as well.

Also, we renamed some files to keep consistency across the project, changed the order of "expected" and "actual" for the tests, and finally we added the [JsonConverter(typeof(SingleOrArrayConverter<Day>))] attribute to MarketData model to replace the if statement for single and multiple days.

Thank you again! Let us know if you have any questions.

**Comment by vitali-karmanov** [comment]
@longpshorn The new version of the NuGet package with the changes you made is now available. https://www.nuget.org/packages/tradier-dotnet-client/

Thank you again!

**Comment by longpshorn** [comment]
Awesome! Thanks guys. Thanks for accepting the changes. I really appreciate the work you guys have already done and that I have been able to build on a little bit. I look forward to continue to working with you on it.

**Pull request merged**
