### PR TITLE
Updating Quote data model to allow for null Bid and Ask values.

### PR DESCRIPTION
**Pull request by longpshorn**
I found that there were cases where the Bid and Ask may be null for certain securities. I included a test case that reflects this is the case. Let me know if you have any questions.

### CODE REVIEW

**Comment by longpshorn** [comment]
Hey guys, any chance you can take a look at this PR? It would be helpful for a project I am working on to get it into the main branch and nuget package.

Thanks,
Patrick

**Comment by vitali-karmanov** [comment]
Hey Patrick, I'm sorry! We are running a little bit late. However, I will be pushing a new nuget package with your changes in a few minutes! Thanks for the changes!

**Comment by longpshorn** [comment]
No worries. Thanks for the response. I appreciate it.

**Comment by vitali-karmanov** [comment]
NuGet Package 1.0.10 is now available with your changes. By the way, Henrique and I will review the other 2 pull requests this week as well! Thanks again!

**Pull request merged**
